### ISSUE TITLE
Adicionar primeiros 10 itens

### ISSUE THREAD

**Issue by teles** [teles/awesome-front-only#1]
Ajuda ae @woliveiras

**Comment by woliveiras** [comment]
Opa, acharemos!

**Comment by woliveiras** [comment]
- http://formspree.io

**Comment by teles** [comment]
Ferramentas para BAAS:

1. Comentários usando o Disqus
2. Buscas usando o Swiftype
3. Formulários usando o getform
4. Formulário usando o formspree
5. Chat usando o Olark
6. Carrinho de compras usando o Snipcart
7. Um sistema de blogs usando jekyll ou hexo
8. Sheetsu para transformar planilha em BD
9. YQL 

Falta 1 pra primeira leva, @woliveiras  hehehe

**Comment by woliveiras** [comment]
* Criar APIS REST : https://www.dreamfactory.com/

**Comment by woliveiras** [comment]
Agora vai mano!? :D

**Comment by teles** [comment]
fechou, @woliveiras !
